### ISSUE TITLE
code tags are not supported e.g. `foo`

### ISSUE THREAD

**Issue by Mouvedia** [Hashnode/hashnode-cli#3]
This [story](https://hashnode.com/post/download-monitoring-a-cross-browser-story-cjqtwrdlt00g9ngs27ij20vob) is filled with blanks. It's unreadable.

**Comment by scriptonist** [comment]
Hey, @Mouvedia thanks for taking the time to let us know about this. The [terminal renderer](https://github.com/scriptonist/termd) used in this project is very young and still a WIP. Features are being added to it iteratively. I'm transferring this issue to the respective project. Please feel free to follow up on this and provide help and suggestions along the way.

**Comment by scriptonist** [comment]
Hey, @Mouvedia thanks for taking the time to let us know about this. The [terminal renderer ](https://github.com/scriptonist/termd) used in this project is very young and still a WIP. Features are being added to it iteratively. I'm closing this issue here and opening a new [issue](https://github.com/scriptonist/termd/issues/1) in the renderer project. Please feel free to follow up on this and provide help and suggestions along the way.

**Comment by Mouvedia** [comment]
You should take a look at [mdless](https://github.com/ttscoff/mdless) or [mdr](https://github.com/mrchimp/mdr).

**Comment by scriptonist** [comment]
Great suggestion @Mouvedia. But we were looking at projects written in **Go** which can be easily imported and used in our project. Please feel free to drop in any such project that you find in your radar. Thanks again 🙏

**Comment by Mouvedia** [comment]
Well then you should maybe start with [goskirt](https://github.com/madari/goskirt).

**Comment by scriptonist** [comment]
Thanks, @Mouvedia will look into it 🙏 , can you attach a screenshot of the issue that you encountered we can maybe use it for future reference?

**Comment by Mouvedia** [comment]
> …can you attach a screenshot of the issue that you encountered…

Sorry I uninstalled it right away and even then it would be useless without context. Text wrapped in `<code></code>` is skipped i.e. you would have to know what is missing beforehand.

> details about the environment

macOS 10.13.6
iTerm2 3.3.20181020-nightly
installed using brew (probably 0.1.8)

**Comment by scriptonist** [comment]
Thanks @Mouvedia, I was wondering if you found something like this 
![image](https://user-images.githubusercontent.com/8335904/51244535-5785cf80-19ab-11e9-93f6-518270722ca2.png)

**Comment by Mouvedia** [comment]
Like I said without context or guessing work you can't tell that something is missing.
e.g. after "findings on"

**Comment by scriptonist** [comment]
Thanks @Mouvedia , really appreciate your help 👍 😃
